### ISSUE TITLE
How to handle parent child relationship using elasticsearch-kafka connector?

### ISSUE THREAD

**Issue by pratikshya** [confluentinc/kafka-connect-elasticsearch#106]
I have an index which has two types, blog and comments (this is for example purpose, the structure is much more complex so can not use nested documents). Blog is parent and comments is child of blog. Using Kafka connector, how would I be able to index these? For example, if I have two elasticsearch sinks - say one for blog, which maps topic to index as blog:indexname and type as blogs another is for comments, which maps topic to index as comments:indexname and type as comments. But seems like I can't map two topics to single index? Correct me if I am wrong. Instead, it creates two separate indices - blog and comments. Looks like topic to index map doesn't even work. How can I pass "parent" or routing information? I am using kafka version 0.10.2.  Also can I run two elasticsearch sinks when running standalone mode or has to be distributed? Any suggestion would be highly appreciated.

**Comment by ewencp** [comment]
By default the topic name is used for the index, which is why you see 2 separate indexes. There is a setting `topic.index.map` that allows you to re-route which index the records end up in. See the configuration documentation on [data conversion](http://docs.confluent.io/current/connect/connect-elasticsearch/docs/configuration_options.html#data-conversion) for more details.

You can actually also use single message transforms for this now too (which didn't exist when the connector was created, thus the connector-specific configuration. See the [transformations documentation](http://kafka.apache.org/documentation.html#connect_transforms), specifically you will want the `RegexRouter`.

**Comment by levzem** [comment]
closing due to question answered and no response
