### ISSUE TITLE
Using TimestampRouter with a static topic format results in a superfluous index being created

### ISSUE THREAD

**Issue by zzbennett** [confluentinc/kafka-connect-elasticsearch#107]
I'm using the Kafka ES connector with the TimestampRouter. I have a topic "foo" that the connector reads from. If I set `transforms.TimestampRouter.topic.format=bar-${timestamp}`, the `foo` index still gets created, but it remains empty. The `bar-${timestamp}` index is created upon indexing the first batch of documents.

I can take a stab at fixing this, but I figured I'd report the issue first in case there is already a fix in progress.

**Comment by ewencp** [comment]
Good catch, it looks like this happens because [indices are created when the consumer is assigned topic partitions](https://github.com/confluentinc/kafka-connect-elasticsearch/blob/master/src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkTask.java#L138) which are not transformed. That might need to be reworked to create indices based on arriving messages to allow it to work correctly with transformations that modify the topic.

**Comment by rmoff** [comment]
Related: https://github.com/confluentinc/kafka-connect-elasticsearch/issues/99

**Comment by levzem** [comment]
this issue is fixed by #275 and exposing a config option `auto.create.indices.at.start`,

thus will be closing.
