### ISSUE TITLE
Unexpected error when registering ES connect

### ISSUE THREAD

**Issue by srijiths** [confluentinc/kafka-connect-elasticsearch#13]
I have an MQTT connector configured in a connect-distributed environment. Then i tried to setup ES Sink connector. I am getting below exception.
![screenshot from 2016-08-03 08 23 19](https://cloud.githubusercontent.com/assets/1046319/17352358/aaba8274-5953-11e6-8962-d5a6240101d8.png)

My ES Sink configuration is like this
![screenshot from 2016-08-03 08 25 22](https://cloud.githubusercontent.com/assets/1046319/17352440/30bb8cd8-5954-11e6-87e9-ea9ddc17e014.png)
Due to this the connect interface itself is failing. Any pointers on this  ? Thanks

**Comment by ewencp** [comment]
This doesn't really look specific to the ES connector. It looks from the stack trace like we're somehow getting a `null` config map somehow. Is the MQTT connector required to reproduce this? Is it reproducible just by running the single command you provided on a new Connect cluster?

**Comment by ewencp** [comment]
@srijiths That seems fine, but I can't reproduce the issue with the sequence of commands you provided. What version of Kafka/Connect are you running? I doubt the combination of MQTT and ES connectors is the issue since the stacktrace doesn't seem like it has anything to do with a conflict.

**Comment by srijiths** [comment]
@ewencp i am using confluvent 3.0.0 version. I tried to register above ES connector again. 

When i observed it has WARN on Concurrent Modification Exception from BulkProcessor class followed by JAVA HEAP SIZE exception. I have 4G alloted to JAVA. Then it follows a series of exceptions and kafka connect , rest evrything stopped. Since its a lengthy stack trace , created a gist. Please see here

https://gist.github.com/srijiths/459725df0137c881090f7a03565f784f

**Comment by shikhar** [comment]
@srijiths this appears to be the root of the problem: `java.lang.OutOfMemoryError: Java heap space`

1. It's possible that the ES connector is buffering so much data that you are running out of heap because of that. `max.buffered.records` defaults to 100000 which is rather high, you could try lowering that.

2. Are you running with customized heap settings? Using the standard scripts, you'd end up with `KAFKA_HEAP_OPTS=-Xmx256M` .You may want to consider growing that to say `512M` if lowering the buffered records config does not help.

**Comment by shikhar** [comment]
Please reopen if there are any unexpected issues here. The defaults for `max.buffered.records` and `batch.size` have been significantly lowered.
