### ISSUE TITLE
Consider mapping string type in a schema to an ES text type with a sub-keyword field

### ISSUE THREAD

**Issue by rayokota** [confluentinc/kafka-connect-elasticsearch#188]
To support ES6, a string type now maps to an ES text type instead of an ES string type, since the string type was deprecated in ES5.  This is the same default behavior as in ES 2.x.   However, now in ES 5.x, the default behavior of ES is to infer a mapping of the following for a string type:

`{ 
          "content" : { 
            "type" : "text", 
            "fields" : { 
              "keyword" : { 
                "type" : "keyword", 
                "ignore_above" : 256 
              } 
            } 
          } 
        } `

We could do the same in the ES connector, possibly adding a configuration property to do one or the other.  Otherwise users can still use a dynamic mapping to get this behavior.

**Comment by rmoff** [comment]
I will +10000 this :) 

A common use case is to put data into Elasticsearch for analysis, and unless we make this option available as part of the connector users will not be able to build viz against aggregatable fields (since `text` cannot be aggregated; `keyword` can) without jumping through the hoops of dynamic mappings. The problem with dynamic mappings is two-fold: 

1. Users will _first_ hit the limitation, and then have to Google around to find out how to resolve it
2. Assuming they find the solution, it's an extra, unnecessary, step that we're asking people to do in building their pipeline.

**Comment by rmoff** [comment]
Written up existing/desired behaviour in more detail in #211

**Comment by rayokota** [comment]
Fixed by https://github.com/confluentinc/kafka-connect-elasticsearch/pull/216
