### ISSUE TITLE
ES Transport Client for bulkprocessor

### ISSUE THREAD

**Issue by pxLi** [confluentinc/kafka-connect-elasticsearch#19]
Hi, I saw the current ES connector is using jest as the ES client.
I have to 2 questions:
1. Is there any plan to add ES transport-layer-client support?
2. What about ES SSL-support, e.g. searchguard or shield?

**Comment by ewencp** [comment]
@pxLi We specifically chose to use jest and the REST API. There are tradeoffs to using either, but the REST API is a better long term solution and we there aren't significant benefits to using the transport client.

re: SSL, we have not added support for this yet, but since jest [supports this](https://github.com/searchbox-io/Jest/tree/master/jest#https--ssl) I'd imagine it's not a huge patch to get support included (though maybe a bit more to also have it well tested).

**Comment by pxLi** [comment]
@ewencp Thanks for your reply!
