### ISSUE TITLE
Convert and write kafka headers into ElasticSearch

### ISSUE THREAD

**Issue by rems** [confluentinc/kafka-connect-elasticsearch#209]
As I understand from [KAFKA-5142](https://issues.apache.org/jira/browse/KAFKA-5142) (see also this [wiki](https://cwiki.apache.org/confluence/display/KAFKA/KIP-145+-+Expose+Record+Headers+in+Kafka+Connect) containing some details) headers are exposed in kafka-connect since kafka 1.1.0.

I'd like to know if there is a plan to support this feature in kafka-connect-elasticsearch, and to which extend (would the transformations described in the wiki be supported ?)

Converting/writing headers would allow to send to ElasticSearch some information like tracability or correlation IDs, that imo are better located in the headers than in the payload of the messages.

In the ElasticSearch side, in order to distinguish fields coming from the message payloads from fields coming from the headers, we might use some prefix, or maybe a sub-document. This choice would idealy be configurable.

I'd like to know your opinion on this.

Thank you

**Comment by levzem** [comment]
@rems the transformations were described in [KIP-145 ](https://cwiki.apache.org/confluence/display/KAFKA/KIP-145+-+Expose+Record+Headers+in+Kafka+Connect) and are being tracked by this [ticket](https://issues.apache.org/jira/browse/KAFKA-8863). Otherwise, the connector will not support its own native support of writing headers as it could be easily accomplished with these SMTs, however they are not implemented yet

**Comment by itng02** [comment]
Do we have an update on when this change will come out?
