### ISSUE TITLE
Release 5.3.0 

### ISSUE THREAD

**Issue by dgthomugo** [confluentinc/kafka-connect-elasticsearch#320]
I really want to use the upsert mode to sink messages to elasticsearch, but when I compile this project according to the wiki FAQ, I always got filed. So please release the v5.3.0 as soon as possible.

**Comment by talaloni2** [comment]
This problem occurs to you because the confluent commons contains an invalid kafka version.
after you install kafka(from apache kafka git repo using gradle), you need to clone the confluent common to your local FS and CHANGE the kafka version in the pom.xml properties section to the installed kafka version(whick i think is 2.4.0 if you performed gradle inastllAll from the current apache  kafka master branch) instead of 5.4.0

**Comment by levzem** [comment]
@dgthomugo v5.3.0 is released.

closing this issue.
