### ISSUE TITLE
Kafka Connect 5.3.1 / Elasticsearch 7 problems

### ISSUE THREAD

**Issue by rmoff** [confluentinc/kafka-connect-elasticsearch#342]
Kafka Connect 5.3.1 with version 5.3.1 of io.confluent.connect.elasticsearch.ElasticsearchSinkTask, running agasinst Elasticsearch 7.3.2

So that fields (e.g. epoch timestamps, geopoints) are picked up correctly, I need to use a dynamic template. 

## Issue 1, dynamic templates in Elasticsearch 7

This used to work < Elasticsearch 7: 

```
curl -XPUT "http://localhost:9200/_template/kafkaconnect/" -H 'Content-Type: application/json' -d'
        {
          "template": "*",
          "settings": {
            "number_of_shards": 1,
            "number_of_replicas": 0
          },
          "mappings": {
            "_default_": {
              "dynamic_templates": [
                {
                  "dates": {
                    "match": "*_TS",
                    "mapping": {
                      "type": "date"
                    }
                  }
                }
              ]
            }
          }
        }'
```

In Elasticsearch 7 now fails [by design](https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html) with 

```
{
  "error": {
    "root_cause": [
      {
        "type": "mapper_parsing_exception",
        "reason": "Root mapping definition has unsupported parameters:  [_default_ : {dynamic_templates=[{dates={mapping={type=date}, match=*_TS}}, {heights={mapping={type=float}, match=HEIGHT}}, {locations={mapping={type=geo_point}, match=LOCATION}}]}]"
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [_default_ : {dynamic_templates=[{dates={mapping={type=date}, match=*_TS}}, {heights={mapping={type=float}, match=HEIGHT}}, {locations={mapping={type=geo_point}, match=LOCATION}}]}]",
    "caused_by": {
      "type": "mapper_parsing_exception",
      "reason": "Root mapping definition has unsupported parameters:  [_default_ : {dynamic_templates=[{dates={mapping={type=date}, match=*_TS}}, {heights={mapping={type=float}, match=HEIGHT}}, {locations={mapping={type=geo_point}, match=LOCATION}}]}]"
    }
  },
  "status": 400
}
```

To get this to work in Elasticsearch 7 

* `template` -> `index_patterns`
* Remove the level below `mappings` (e.g. `_default_` above) since ES7 https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html[deprecated mapping types]

    ```
    {
        "index_patterns": "*",
            "settings": {
            "number_of_shards": 1,
            "number_of_replicas": 0
            },
        "mappings": {
            "dynamic_templates": [
                {
                    "dates": {
                        "match": "*_TS",
                        "mapping": {
                            "type": "date"
                        }
                    }
                }
            ]
        }
    }'
    ```

## Issue 2, Kafka Connect support for Elasticsearch 7

BUT NOW we have another problem. With a dynamic template in place, Kafka Connect Elasticsearch sink fails. 

    {
    "type": "illegal_argument_exception",
    "reason": "Rejecting mapping update to [runner_status] as the final mapping would have more than 1 type: [_doc, type.name=kafkaconnect]"
    }

Full error: 

    [2019-09-25 19:45:01,040] WARN Encountered an illegal document error when executing batch 120 of 1 records. Ignoring and will not index record. Error was [{"type":"illegal_argument_exception","reason":"Rejecting mapping update to [runner_status] as the final mapping would have more than 1 type: [_doc, type.name=kafkaconnect]"}] (io.confluent.connect.elasticsearch.bulk.BulkProcessor:416)

Example Kafka Connect connector config: 

```
curl -i -X PUT -H  "Content-Type:application/json" \
      http://localhost:8083/connectors/sink-elastic-cloud-runner_location-00/config \
      -d '{
            "connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
            "connection.url": "http://localhost:9200",
            "type.name": "type.name=kafkaconnect",
            "behavior.on.malformed.documents": "warn",
            "topics": "RUNNER_LOCATION",
            "key.ignore": "true",
            "schema.ignore": "true"
            }'
```

If you change `"type.name": "type.name=kafkaconnect",` to `"type.name": "type.name=_doc"` you get the same error: 

    {
        "type":"illegal_argument_exception",
        "reason":"Rejecting mapping update to [runner_status] as the final mapping would have more than 1 type: [_doc, type.name=_doc]"
    }

Only option is to *remove the dynamic template*, and then the connector will work—but now you don't get your field types set.

Exact same error if you create a static mapping for specific index. 

Only option I've found so far is to move back to Elasticsearch 6, at which point everything works as it should :) 

Related: #314

**Comment by strigona-worksight** [comment]
I'm not 100% sure here, but when we tested this out (successfully) we set `"type.name": ""` in Kafka Connector config,

**Comment by rmoff** [comment]
This is what I ran against ES7 , including `include_type_name`

```
curl -XPUT "http://localhost:9200/_template/kafkaconnect/?include_type_name=true" 
        -H 'Content-Type: application/json' -d'
{
            "template": "*",
            "settings": { "number_of_shards": 1, "number_of_replicas": 0 },
            "mappings": { "_default_" : {
                "dynamic_templates": [
                    { "dates": { "match": "*_TS", "mapping": { "type": "date" } } },
                    { "heights": { "match": "HEIGHT", "mapping": { "type": "float" } } },
                    { "locations": { "match": "LOCATION", "mapping": { "type": "geo_point" } } }
                ] } } }'
```

**Comment by Duchadian** [comment]
> BUT NOW we have another problem. With a dynamic template in place, Kafka Connect Elasticsearch sink fails

What I think is happening here is that you are confusing the type of the document with the name of the template in Elasticsearch. The curl command above does not create a type "kafkaconnect", but a type _doc, i.e. the default.

> If you change "type.name": "type.name=kafkaconnect", to "type.name": "type.name=_doc" you get the same error

> curl -XPUT "http://localhost:9200/_template/kafkaconnect/?include_type_name=true" 
        -H 'Content-Type: application/json' -d'
{
            "template": "*",
            "settings": { "number_of_shards": 1, "number_of_replicas": 0 },
            "mappings": { "_default_" : {
                "dynamic_templates": [
                    { "dates": { "match": "*_TS", "mapping": { "type": "date" } } },
                    { "heights": { "match": "HEIGHT", "mapping": { "type": "float" } } },
                    { "locations": { "match": "LOCATION", "mapping": { "type": "geo_point" } } }
                ] } } }'

It seems to me that the response you are getting here is also correct. The configuration should be "type.name': "_doc" based on the index pattern you have defined. It is looking for the literal string "type.name=_doc" when trying to index the document.

**Comment by purbon** [comment]
Hi @rmoff looking at this issue right now. I keep the issue updated with thoughts.

**Comment by purbon** [comment]
@rmoff speaking about issue 1 as described by your post, I can't see how this is related to the connector, do you mind helping me? This issue is related to the changes introduced by Elasticsearch 7.

**Comment by purbon** [comment]
@rmoff now talking about issue 2, 

I think there is a typo in the type name of your config, you use something like:

```
   "type.name": "type.name=kafkaconnect",
```
why not
```
            "type.name": "_doc",
```
this value is passed directly into the createMapping function, as you can see:

```java
if (Mapping.getMapping(client, index, type) == null) {
            Mapping.createMapping(client, index, type, sinkRecord.valueSchema());
          }
```

and is passed directly into elastic during index creation. Might be what we're seeing here is an issue with the config validation? 

As noted by @Duchadian as well, I see probably an improvement proposal here and is a proper template handling by the connector, but this might be a discussion for another issue.

**Comment by Duchadian** [comment]
@purbon @rmoff 
> Might be what we're seeing here is an issue with the config validation?
As far as my understanding of Elasticsearch goes, this is _sort of_ what is happening. When a document is indexed into Elasticsearch, the type mapping of the document in question is tested against the type mapping that is present for an index. This is done by checking which fields in the document match to the fields defined in the template.

In Elasticsearch 5 and lower, if the document matches to more than type, the document is still indexed (although I do believe that Elasticsearch raised a warning in its own log). In Elasticsearch 6 and higher, the document is NOT indexed, and an error like this is raised:
`
{
"type": "illegal_argument_exception",
"reason": "Rejecting mapping update to [runner_status] as the final mapping would have more than 1 type: [_doc, type.name=kafkaconnect]"
}
`
The problem we are seeing results from attempting to index a document that matches **more** than one type. Because an _doc type is present that matches the document, and the document itself states its type as being _kafkaconnect_ , Elasticsearch 6 and higher rejects the document.

**Comment by purbon** [comment]
Hi @Duchadian thanks for your answer.

I agree with your observation, but using types in elasticsearch has been discouraged as a bad practise for many, many years.  

Having said that, I wonder is a config that contains

```
   "type.name": "type.name=kafkaconnect",
``` 

does not feels correct to me.

but as well all this started with a dynamic template being created outside the connector, unless the template is in control of the connector this is outside of the things the connector can improve. I'm I missing anything?

**Comment by Duchadian** [comment]
Hi @purbon, I totally agree, on both the use of types and the configuration. 

In my opinion, it is usually best to not touch _type in Elasticsearch 6+ unless you _really_ have to. 

I think it might be fruitful to add some documentation regarding the use of templates, with specific mention to avoid adding extra types. If you really _have_ to change the template to get specific functionality (as @rmoff was doing), it would likely be best to update the template that (I believe) is pushed by the connector.

**Comment by purbon** [comment]
I like the idea of templates pushed by the connector, so I'm +1 on that!

Speaking about the current user experience. What we could do is probably, raise an error if:

* You are targeting ES 7 (we know that info)
* You aim to use a type that is not _doc.

Does this help? 

@rmoff @rhauch  what do you think?

**Comment by purbon** [comment]
As described in 

<img width="764" alt="Screen Shot 2019-10-04 at 19 25 15" src="https://user-images.githubusercontent.com/68540/66227106-c5f6f300-e6dc-11e9-86a6-2a75cf295833.png">

and as used in the test, that run with Elasticsearch 7.0 using TestContainers, see https://github.com/confluentinc/kafka-connect-elasticsearch/blob/master/src/test/java/io/confluent/connect/elasticsearch/integration/MappingIT.java#L37

I'm actually thinking out loud, but might be @rmoff can confirm:

* The template was created without specify a mapping, so _doc was used.
* If the template would have been created with the expected type (_type.name=kafkaconnect_), no error would have shown.
* Another error is the 2 mapping error during document creation due to adding the type information in the call using the jest client.

Does this makes sense?

**Comment by Duchadian** [comment]
@purbon , I fully agree with your last comment. 

> If ES.version>6 is used, get the mapping for the destination index (if available) and raise an error if a type other than the expected is used.

I think this nuance compared to your previous comment is important. I don't think it matters if the user is using another type than _doc, _as long as the type is the same as the type the connector is expecting._ 

Besides that, no comments.

**Comment by rmoff** [comment]
Thanks for all the input & help @Duchadian @purbon @strigona-worksight. As you can tell I am not an Elasticsearch expert so this has taken some flailing around, plus a silly typo in my config (`   "type.name": "type.name=kafkaconnect",` as @purbon spotted) didn't help. 

I can confirm that Kafka Connect Elasticsearch 5.3.1 works very happily with Elasticsearch 7.4. I create a template: 

```
curl -XPUT "http://localhost:9200/_template/kafkaconnect/" \
        -H 'Content-Type: application/json' -d \
        ' {
            "template": "*",
            "settings": {
                "number_of_shards": 1,
                "number_of_replicas": 0
            },
            "mappings": {
                    "dynamic_templates": [
                        {
                            "dates": {
                                "match": "*_TS",
                                "mapping": {
                                    "type": "date"
                                }
                            }
                        },
                        {
                            "heights": {
                                "match": "HEIGHT",
                                "mapping": {
                                    "type": "float"
                                }
                            }
                        },
                        {
                            "locations": {
                                "match": "LOCATION",
                                "mapping": {
                                    "type": "geo_point"
                                }
                            }
                        }
                    ]
                }
            }
        }'
```

Then I create a connector, with `type_name` set to blank: 

```
curl -i -X PUT -H  "Content-Type:application/json" \
            http://localhost:8083/connectors/sink-elastic-07/config \
            -d '{
                    "connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
                    "connection.url": "http://elasticsearch:9200",
                    "type.name": "",
                    "behavior.on.malformed.documents": "warn",
                    "topics": "RUNNER_LOCATION_00",
                    "key.ignore": "true",
                    "key.converter":"org.apache.kafka.connect.storage.StringConverter",
                    "schema.ignore": "true"
                    }'
```

Documents are indexed under the `_doc` type: 

    curl -XPOST -s "http://localhost:9200/runner_location_00/_search" | jq '.hits.hits[0]._type'
    "_doc"

Mappings are correctly picked up from the template: 

```
curl -XGET -s "http://localhost:9200/runner_location_00/_mapping" | jq '.runner_location_00.mappings.properties.LOCATION'
{
  "type": "geo_point"
}
```

**Comment by rivernews** [comment]
> Hi @Duchadian thanks for your answer.
> 
> I agree with your observation, but using types in elasticsearch has been discouraged as a bad practise for many, many years.
> 

Just want to  make sure my understanding on `type.name` is correct - so when configuring elasticsearch sink connector, should we view `type.name` as a deprecated field for elasticsearch 7+?

Based on the discussion here and my experience, setting `type.name` to things other than `_doc` will cause the error `final mapping would have more than 1 type`.  My guess about why this field exists is that it's for versions before elasticsearch 6 to let user specify a custom mapping name, but no longer useful for elasticsearch 7+ given the change of removal of type.

I'm still learning kafka so correct me if I'm wrong. I think what kind of confuses me is [current doc](https://docs.confluent.io/current/connect/kafka-connect-elasticsearch/configuration_options.html#data-conversion) implies that `type.name` is a required/high importance field but did not mention the issue with elasticsearch 7+. On the other hand, many examples on the Internet still configure it as `type.name=kafka-connect` (but yes, if their elasticsearch version is 6 or earlier it will work. Just thought that new users might go for latest elasticsearch and will run into the same issue here)

I currently set it as `type.name=_doc` and it's working. Just want to see if there will be any change or withdrawal of `type.name` in the properties configuration in the future. Or if `type.name` has other use that I am missing and it is not going to go deprecated any sooner, would love to know the considerations so that we know how to configure it properly.

**Comment by Duchadian** [comment]
> Just want to make sure my understanding on type.name is correct - so when configuring elasticsearch sink connector, should we view type.name as a deprecated field for elasticsearch 7+?

@rivernews , I hope I'm not jumping the gun ahead of a Confluent employee's answer by saying that `type.name` should be considered deprecated. If not for this version, then it should be for the upcoming Elasticsearch 8 release. The current solution in the connector for indexing documents for Elasticsearch 7 is a workaround that will no longer work for Elasticsearch 8. That is, if the intent is to use this exact repo for ES 8 also. 

> Based on the discussion here and my experience, setting type.name to things other than _doc will cause the error final mapping would have more than 1 type. 

That is correct due to the default mapping type for ES 7 being _doc, which can be changed manually by deleting the mapping and overriding it with another type name. This is no longer recommended for ES 7, and will not be possible in ES 8 and up. 

i agree with the rest of what you're saying. The documentation should accommodate the change for ES 7. Otherwise, new users of this connector will likely end up searching for a solution for a longer time than necessary.

**Comment by thecloudgarage** [comment]
I ran into the same issue and a long search to have include type appended to the PUT for template creation

**Comment by rmoff** [comment]
For future Googlers: `type.name` is deprecated and was [removed from Kafka Connect Elasticsearch connector from version 11 onwards](https://docs.confluent.io/kafka-connect-elasticsearch/current/changelog.html#version-11-0-0).
