### ISSUE TITLE
Elasticsearch connector error:  javax.net.ssl.SSLProtocolException: Connection reset

### ISSUE THREAD

**Issue by emy-lee** [confluentinc/kafka-connect-elasticsearch#371]
Hello everyone, I have an error with the elasticsearch connector. 
The connector works for a while, it sends some thousands of messages and then after some time, it stops and I get this error. 

```
name	"elasticsearch-sink"
connector	
state	"RUNNING"
worker_id	"xxx.xxx.xxx.xxx:8083"
tasks	
0	
id	0
state	"FAILED"
worker_id	"xxx.xxx.xxx.xxx:8083"
trace	"org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:560)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:321)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)\n\tat org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)\n\tat org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:834)\nCaused by: org.apache.kafka.connect.errors.ConnectException: javax.net.ssl.SSLProtocolException: Connection reset\n\tat io.confluent.connect.elasticsearch.jest.JestElasticsearchClient.indexExists(JestElasticsearchClient.java:284)\n\tat io.confluent.connect.elasticsearch.jest.JestElasticsearchClient.createIndices(JestElasticsearchClient.java:290)\n\tat io.confluent.connect.elasticsearch.ElasticsearchWriter.write(ElasticsearchWriter.java:255)\n\tat io.confluent.connect.elasticsearch.ElasticsearchSinkTask.put(ElasticsearchSinkTask.java:169)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:538)\n\t... 10 more\nCaused by: javax.net.ssl.SSLProtocolException: Connection reset\n\tat java.base/sun.security.ssl.Alert.createSSLException(Alert.java:126)\n\tat java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)\n\tat java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)\n\tat java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:259)\n\tat java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1314)\n\tat java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:839)\n\tat org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)\n\tat org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)\n\tat org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)\n\tat org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)\n\tat org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)\n\tat org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)\n\tat org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)\n\tat org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)\n\tat org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)\n\tat org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)\n\tat org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)\n\tat org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)\n\tat org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)\n\tat org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)\n\tat org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)\n\tat org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)\n\tat io.searchbox.client.http.JestHttpClient.executeRequest(JestHttpClient.java:133)\n\tat io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:70)\n\tat io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:63)\n\tat io.confluent.connect.elasticsearch.jest.JestElasticsearchClient.indexExists(JestElasticsearchClient.java:281)\n\t... 14 more\nCaused by: java.net.SocketException: Connection reset\n\tat java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)\n\tat java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)\n\tat java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:448)\n\tat java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:68)\n\tat java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1104)\n\tat java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:823)\n\t... 34 more\n"
```

This is the configuration of the connector:

```
name    "elasticsearch-sink"
config    
connector.class    "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector"
type.name    "kafka-connect"
connection.password    ""
tasks.max    "1"
connection.timeout.ms    "30000"
key.ignore    "true"
internal.key.converter.schemas.enable    "false"
elastic.https.ssl.truststore.password    "password"
value.converter    "io.confluent.connect.avro.AvroConverter"
read.timeout.ms    "300000"
key.converter    "io.confluent.connect.avro.AvroConverter"
elastic.https.ssl.truststore.type    "JKS"
topics    "uuu.test.kkk,uuu.test.vvv,uuu.test.ppp,uuu.test.ooo,uuu.test.vvv,uuu.test.fff,uuu.test.qqq"
connection.username    "elastic"
value.converter.schema.registry.url    "http://xxx.xxx.xxx.xxx:8081,http://xxx.xxx.xxx.xxx:8081,http://xxx.xxx.xxx.xxx:8081"
internal.key.converter    "org.apache.kafka.connect.json.JsonConverter"
flush.timeout.ms    "30000"
elastic.https.ssl.protocol    "TLS"
topic.index.map    "uuu.test.kkk:kkkvalue,uuu.test.vvv:vvvvalue,uuu.test.ppp:pppvalue,uuu.test.ooo:oldooovalue,uuu.test.vvv:vvvvalue,uuu.test.fff:fffvalue,uuu.test.qqq:qqqvalue"
internal.value.converter.schemas.enable    "false"
name    "elasticsearch-sink"
internal.value.converter    "org.apache.kafka.connect.json.JsonConverter"
connection.url    "https://xx.xxx.com:9200"
key.converter.schema.registry.url    "http://xxx.xxx.xxx.xxx:8081,http://xxx.xxx.xxx.xxx:8081,http://xxx.xxx.xxx.xxx:8081"
elastic.https.ssl.truststore.location    "/kafka/test-certs/test.server.truststore.jks"
tasks    
0    
connector    "elasticsearch-sink"
task    0
type    "sink"
```

Any idea?

**Comment by levzem** [comment]
@emy-lee can you please provide the full stacktrace and formatted in a more readable way?

**Comment by levzem** [comment]
closing due to no response - please feel free to reopen if you still need help

**Comment by vf88** [comment]
Hi there, 
I have the same issue. It would be great if you provide some info regarding this exception

"trace": "org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:560)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:321)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)\n\tat org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)\n\tat org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)\n\tat java.base/java.util.concurrent.FutureTask.run(Unknown Source)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)\n\tat java.base/java.lang.Thread.run(Unknown Source)\nCaused by: org.apache.kafka.connect.errors.ConnectException: javax.net.ssl.SSLException: Connection reset\n\tat io.confluent.connect.elasticsearch.jest.JestElasticsearchClient.indexExists(JestElasticsearchClient.java:284)\n\tat io.confluent.connect.elasticsearch.jest.JestElasticsearchClient.createIndices(JestElasticsearchClient.java:290)\n\tat io.confluent.connect.elasticsearch.ElasticsearchWriter.write(ElasticsearchWriter.java:255)\n\tat io.confluent.connect.elasticsearch.ElasticsearchSinkTask.put(ElasticsearchSinkTask.java:169)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:538)\n\t... 10 more\nCaused by: javax.net.ssl.SSLException: Connection reset\n\tat java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)\n\tat java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)\n\tat java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)\n\tat java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)\n\tat java.base/sun.security.ssl.SSLSocketImpl.handleException(Unknown Source)\n\tat java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(Unknown Source)\n\tat org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)\n\tat org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)\n\tat org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)\n\tat org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)\n\tat org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)\n\tat org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)\n\tat org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)\n\tat org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)\n\tat org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)\n\tat org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)\n\tat org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)\n\tat org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)\n\tat org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)\n\tat org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)\n\tat org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)\n\tat org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)\n\tat io.searchbox.client.http.JestHttpClient.executeRequest(JestHttpClient.java:133)\n\tat io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:70)\n\tat io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:63)\n\tat io.confluent.connect.elasticsearch.jest.JestElasticsearchClient.indexExists(JestElasticsearchClient.java:281)\n\t... 14 more\n\tSuppressed: java.net.SocketException: Broken pipe (Write failed)\n\t\tat java.base/java.net.SocketOutputStream.socketWrite0(Native Method)\n\t\tat java.base/java.net.SocketOutputStream.socketWrite(Unknown Source)\n\t\tat java.base/java.net.SocketOutputStream.write(Unknown Source)\n\t\tat java.base/sun.security.ssl.SSLSocketOutputRecord.encodeAlert(Unknown Source)\n\t\t... 39 more\nCaused by: **java.net.SocketException: Connection reset**\n\tat java.base/java.net.SocketInputStream.read(Unknown Source)\n\tat java.base/java.net.SocketInputStream.read(Unknown Source)\n\tat java.base/sun.security.ssl.SSLSocketInputRecord.read(Unknown Source)\n\tat java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(Unknown Source)\n\tat java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(Unknown Source)\n\t... 35 more\n"
