### ISSUE TITLE
Disable index creation completely

### ISSUE THREAD

**Issue by jkarteek** [confluentinc/kafka-connect-elasticsearch#439]
@levzem Is there any way to disable index creation completely. We are using the new data streams to write logs to ES and thus don't require index creation. Is there any way to avoid this?

**Comment by levzem** [comment]
precreate the indexes that you need, set `auto.create.indices.at.start` to false and use an SMT to change the topic of the record to point to the indices you desire

**Comment by jkarteek** [comment]
Ahh thought so. The issue is that the index name is cannot be pre-determined in our case, as services may come and go (and external services can changes names which is beyond our control).

It would probably make more sense for us to just fork the repo and add a flag (something like auto.create.indices). 

Does it make sense for this change to be merge into the repo? If so I could raise a PR.

**Comment by levzem** [comment]
@jkarteek in that case, yes the only solution would be to fork the connector. I don't think that this feature particularly makes sense at this time as it is extremely use case specific. If you would still like to open a PR, feel free to do so, we can have a look at it sometime in the future if it turns out we need that feature.

**Comment by jkarteek** [comment]
@levzem Thanks for the help. I will close the issue for now
