### ISSUE TITLE
ES 5.0 compatibility

### ISSUE THREAD

**Issue by shikhar** [confluentinc/kafka-connect-elasticsearch#55]
Let's track known issues here.

1. The mapping from `Schema.Type.STRING` to `string` fails because is is not a valid ES type anymore (https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_50_mapping_changes.html)

**Comment by ewencp** [comment]
@shikhar Would probably be good to get the system tests to run against ES 5.0 too, will probably reveal many issues.

**Comment by jozi-k** [comment]
So ES 5.x is not yet supported by this library?

**Comment by otisg** [comment]
Same question here...

**Comment by azell** [comment]
I believe that one of the issues with using the *string* type in ES 5 is combining it with *null_value*.   Omitting the *null_value* setting allows ES 5 to create the mapping.

**Comment by ewencp** [comment]
It's not fully supported yet (though note that you can still use it -- just the incompatibility noted above). This should get closed once ES 5 support is resolved.

**Comment by rusrushal13** [comment]
Is this issue is still open?
I would like to work on it :smile:

**Comment by babadofar** [comment]
elasticsearch 5.0 will silently convert string to the new text field data type, but in 6.0 this fails miserably.  
This line:
https://github.com/confluentinc/kafka-connect-elasticsearch/blob/e5aec607552973f217d18f39a982caa57663ca66/src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConstants.java#L36

**Comment by wicknicks** [comment]
For ES 6.0 and above, the string type has been completely removed. In order to get the existing elasticsearch-connector to work with ES,  we can set `schema.ignore` to `true` in the connector configuration. This will skip creating the mappings which causes the tasks to fail. 

Importing the data will work with the above workaround. When the mappings are not specified, ES server will detect the type using the field mapping rules specified [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-field-mapping.html). A string in your JSON document will most likely be converted into a text type and a keyword type (if it's within the length limits). This will allow full text searches on the analyzed text.

**Comment by synhershko** [comment]
See https://github.com/confluentinc/kafka-connect-elasticsearch/issues/154#issuecomment-357499243

**Comment by rayokota** [comment]
This is fixed with #169
