### ISSUE TITLE
Match all topics with pattern

### ISSUE THREAD

**Issue by treziac** [confluentinc/kafka-connect-elasticsearch#65]
Hi,

Is it possible, instead of passing a list of topics in "topics" config, to pass a template (ex: event.member.* will match all kafka topics starting with event.member. and place them in the corresponding index), which would also scan for newly ceated topics?

**Comment by tslater** [comment]
I'm trying to figure out the same thing. I get ```
[pool-1-thread-3] WARN org.apache.kafka.clients.NetworkClient - Error while fetching metadata with correlation id 105 : {topicprefix.*=INVALID_TOPIC_EXCEPTION}
```

**Comment by ewencp** [comment]
@treziac & @tslater That's actually a config that's common to all sink connectors and defined by the Kafka Connect framework. That feature is currently missing -- we have https://issues.apache.org/jira/browse/KAFKA-3073 filed to track that request in Kafka.

I'm going to close this for now since this is already tracked in the Kafka project, but reopen if you have any further questions/clarifications.

**Comment by kmillanr** [comment]
> @treziac & @tslater That's actually a config that's common to all sink connectors and defined by the Kafka Connect framework. That feature is currently missing -- we have https://issues.apache.org/jira/browse/KAFKA-3073 filed to track that request in Kafka.
> 
> I'm going to close this for now since this is already tracked in the Kafka project, but reopen if you have any further questions/clarifications.

Hello, it has been 2 years. Was this ever solved?
