### ISSUE TITLE
Offset Commit Timed Out

### ISSUE THREAD

**Issue by johnpaullarsen** [confluentinc/kafka-connect-elasticsearch#74]
I've got a connector set up with a constant low volume stream of messages (10/min). While everything seems to work fine the following warning is being logged at regular intervals:

WARN Commit of WorkerSinkTask{id=elastic-authenticatedcall-sink-2} offsets timed out

The storage topics are configured as specified here http://docs.confluent.io/3.2.0/connect/userguide.html#distributed-worker-configuration

Timeouts are set to the defaults (which seem generous)

The kafka cluster is running 3 nodes and has essentially no load. Everything appears to work fine, and when stopping and starting the connector it appears to pick up where it left off. 

Can anyone shed any light on this warning? Should I be concerned?

**Comment by ewencp** [comment]
Is there any other info in the log about these errors? The timeout may not strictly be a problem in the sense that the final step in committing offsets is to write those offsets to a Kafka topic. That write may timeout, but that doesn't necessarily mean it failed.

If the time between the start of commit and timeout is very small, then it sounds like this could be a case of https://issues.apache.org/jira/browse/KAFKA-4942 which looks like a regression in 0.10.2.0. Hopefully we can get a fix into 0.10.2.1, but as I said, in the meantime, just the timeout is not an indication it completely failed (which is why we have it at WARN, whereas a true error would get logged at a higher level).

**Comment by johnpaullarsen** [comment]
I can confirm this is the exact same issue as https://issues.apache.org/jira/browse/KAFKA-4942

**Comment by jomach** [comment]
I have the exact same problem. On confluent 3.3.0

**Comment by FS1360472174** [comment]
+1， how to fix this

**Comment by jomach** [comment]
@FS1360472174  My problem was that the super.users were configured wrong on cloudera.

**Comment by FS1360472174** [comment]
@jomach thanks,my problem is es cluster is not work well
